# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class BbaeSpiderItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    fund_name = scrapy.Field()
    closing_price = scrapy.Field()
    day_change = scrapy.Field()
    morningstar_category = scrapy.Field()
    volume = scrapy.Field()
    exchange = scrapy.Field()
    ISIN = scrapy.Field()
    fund_size_mil = scrapy.Field()
    # ongoing_charge = scrapy.Field()
    category = scrapy.Field()
    category_benchmark = scrapy.Field()
    morningstar_research = scrapy.Field()
    morningstar_sustainability = scrapy.Field()
    sustainability_mandate = scrapy.Field()
    percent_rank_in_category = scrapy.Field()
    sustainability_score = scrapy.Field()
    investment_objective = scrapy.Field()
    trailing_returns = scrapy.Field()
    YTD = scrapy.Field()
    three_years_annualised = scrapy.Field()
    five_years_annualised = scrapy.Field()
    ten_years_annualised = scrapy.Field()
    fund_benchmark = scrapy.Field()
    morningstar_benchmark = scrapy.Field()
    style_box_src = scrapy.Field()
    style_box = scrapy.Field()
    stock_long = scrapy.Field()
    stock_short = scrapy.Field()
    stock_net_assets = scrapy.Field()
    bond_long = scrapy.Field()
    bond_short = scrapy.Field()
    bond_net_assets = scrapy.Field()
    property_long = scrapy.Field()
    property_short = scrapy.Field()
    property_net_assets = scrapy.Field()
    cash_long = scrapy.Field()
    cash_short = scrapy.Field()
    cash_net_assets = scrapy.Field()
    other_long = scrapy.Field()
    other_short = scrapy.Field()
    other_net_assets = scrapy.Field()
    top_5_regions = scrapy.Field()
    top_5_regions_percent = scrapy.Field()
    top_5_sectors = scrapy.Field()
    top_5_sectors_percent = scrapy.Field()
    top_5_holdings = scrapy.Field()
    top_5_holdings_sector = scrapy.Field()
    top_5_holdings_percent = scrapy.Field()

    portfolio_title = scrapy.Field()
    size_name = scrapy.Field()
    size_value = scrapy.Field()
    size_rel_to_cat = scrapy.Field()
    # market_capitalisation = scrapy.Field()
    # market_capitalisation_equity = scrapy.Field()
    market_capitalisation_giant_equity = scrapy.Field()
    market_capitalisation_large_equity = scrapy.Field()
    market_capitalisation_medium_equity = scrapy.Field()
    market_capitalisation_small_equity = scrapy.Field()
    market_capitalisation_micro_equity = scrapy.Field()

    valuations_and_growth_rates = scrapy.Field()
    equity_portfolio = scrapy.Field()
    world_regions = scrapy.Field()
    world_regions_equity = scrapy.Field()
    world_regions_relative_to_category = scrapy.Field()
    relative_to_category = scrapy.Field()
    sector_weightings = scrapy.Field()
    sector_weightings_equity = scrapy.Field()
    sector_weightings_relative_to_category = scrapy.Field()
    # top_10_holdings_summary = scrapy.Field()
    # top_10_holdings_summary_portfolio = scrapy.Field()
    total_number_of_equity_holdings = scrapy.Field()
    total_number_of_equity_holdings_portfolio = scrapy.Field()
    total_number_of_bond_holdings = scrapy.Field()
    total_number_of_bond_holdings_portfolio = scrapy.Field()
    top_10_holdings = scrapy.Field()
    top_10_holdings_portfolio = scrapy.Field()

    top_10_holdings_name = scrapy.Field()
    top_10_holdings_sector = scrapy.Field()
    top_10_holdings_country = scrapy.Field()
    top_10_holdings_percent_of_assets = scrapy.Field()

    name_of_company = scrapy.Field()
    phone = scrapy.Field()
    website = scrapy.Field()
    address = scrapy.Field()
    domicile = scrapy.Field()
    legal_structure = scrapy.Field()
    UCITS = scrapy.Field()
    inception_date = scrapy.Field()
    fund_advisor = scrapy.Field()
    fund_managers = scrapy.Field()
    manager_start_dates = scrapy.Field()
    biographies = scrapy.Field()

    max_initial_charge = scrapy.Field()
    max_exit_charge = scrapy.Field()
    max_annual_management_charge = scrapy.Field()
    ongoing_charge = scrapy.Field()
    minimum_investments_initial = scrapy.Field()
    minimum_investments_additional = scrapy.Field()
    minimum_investments_savings = scrapy.Field()
    tax_free_savings_schemes_purchase_details = scrapy.Field()

